

INSERT INTO bouquets (name, price, currency, description, image)
VALUES ('love is kind',
        75,
        'USD',
        'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.',
        '/products/loveIsKind.jpeg' ),
        ('lavender dreams',
        55,
        'USD',
        'A mixed arrangement of fragrant roses and sweet smelling stocks.',
        '/products/lavender.jpeg'),
        ('dozen of roses',
        125,
        'USD',
        'Rose is not just a flower ,a symbol of love, beauty, and elegance that transcends time.',
        '/products/rose.jpeg'),
        ('happiness',
        100,
        'USD',
        'A beautiful arrangement of fresh mixed blooms, arranged in a low compact design.',
        '/products/happiness.jpeg'),
        ('rose and tulips', 
        75,
        'USD',
        'A beautiful bubble bowl arrangement filled with fun and joy-filled color.',
        '/products/rose-and-tulips.jpeg'),
        ('saturday',
        55,
        'USD',
        'If you’re going to rise, you might as well shine!',
        '/products/saturday.jpeg'

        ),
        ('summer',
        50,
        'USD',
        'The perfect blooms for a summer picnic.',
        '/products/summer.jpeg'
        ),
        ('ballons',
        10,
        'USD',
        'What a surprise! Balloons for the Birthday party/Celebrate',
        '/products/balloons.jpeg'

        ),
        ('bear',
        35,
        'USD',
        'You are the cutest bear',
        '/products/bear.jpeg'
        ),
        ('chocolate basket',
        45,
        'USD',
        'celebrate with chocolate',
        '/products/chocolate.jpeg'
        ),
        ('white and purple',
        50,
        'USD',
        'This is all you need',
        '/products/purple.jpeg'
        ),
        ('colorful mix',
        75,
        'USD',
        'colordul mix arrangment is shining your day',
        '/products/colorful.jpeg'
        ),
        ('love',
        57,
        'USD',
        'love is love',
        '/products/love.jpeg'),
        ('get well',
        45,
        'USD',
        'wish you get better soon',
        '/products/getwell.jpeg'),
        ('single sunflower',
        15,
        'USD',
        'You are special',
        '/products/sunflower.jpeg'),
        ('get well 2',
        55,
        'USD',
        'think of you',
        '/products/getwell2.jpeg')
        ;
INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'joel@joelburton.com',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'joel@joelburton.com',
        TRUE);
INSERT INTO transactions (user_id, bouquet_id,quantity,total_price)
VALUES ('testuser',1,1,75),
        ('testadmin',1,1,75);        